"""Copywriting stage — generates content variants from research."""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from content_automata.models import ContentBrief, Draft, ResearchResult

logger = logging.getLogger(__name__)


class CopyWriter:
    """Generates content copy from research data.

    Produces blog posts, social media copy, and ad copy variants
    with configurable tone customization.
    """

    SUPPORTED_TONES = ["professional", "casual", "persuasive", "humorous", "authoritative"]

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self._config = config or {}
        self._default_tone = self._config.get("copywriting", {}).get(
            "default_tone", "professional"
        )
        self._variants = self._config.get("copywriting", {}).get(
            "variants", ["blog", "social", "ad"]
        )
        self._api_key = self._config.get("api_key", "")
        logger.info(
            f"CopyWriter initialized: tone='{self._default_tone}', "
            f"variants={self._variants}"
        )

    def generate(
        self, research: ResearchResult, brief: ContentBrief
    ) -> Draft:
        """Generate content drafts from research results.

        Args:
            research: The research results to base content on.
            brief: The content brief with tone and formatting preferences.

        Returns:
            A Draft containing all generated content variants.
        """
        tone = brief.tone or self._default_tone
        if tone not in self.SUPPORTED_TONES:
            logger.warning(f"Unknown tone '{tone}', falling back to 'professional'")
            tone = "professional"

        topic = research.topic
        key_points = research.key_points
        outline = research.outline

        logger.info(f"Generating {tone} content for '{topic}'")

        blog_post = self._generate_blog_post(topic, key_points, outline, tone)
        social_copy = self._generate_social_copy(topic, key_points, tone)
        ad_copy = self._generate_ad_copy(topic, key_points, tone)
        headline = self._generate_headline(topic, tone)
        meta_description = self._generate_meta_description(topic, key_points)

        word_count = len(blog_post.split()) if blog_post else 0

        return Draft(
            blog_post=blog_post,
            social_copy=social_copy,
            ad_copy=ad_copy,
            headline=headline,
            meta_description=meta_description,
            tone=tone,
            word_count=word_count,
        )

    def _generate_blog_post(
        self, topic: str, key_points: List[str], outline: str, tone: str
    ) -> str:
        """Generate a full blog post from research."""
        greeting = self._tone_greeting(tone)
        closing = self._tone_closing(tone)

        post = f"""# {topic}

{greeting}

## Introduction

{topic} is transforming how businesses operate and compete. In this post, we'll explore the key aspects you need to know to stay ahead of the curve.

## Why {topic} Matters Now

The landscape is evolving rapidly. Organizations that embrace these changes early are seeing significant advantages in efficiency, customer satisfaction, and revenue growth.

## Key Insights

"""
        for i, point in enumerate(key_points[:5], 1):
            post += f"{i}. **{point}** — This represents a critical consideration for anyone looking to leverage {topic} effectively.\n\n"

        post += f"""## Practical Applications

There are several ways to apply {topic} in real-world scenarios:

1. **Assessment** — Evaluate your current processes and identify opportunities.
2. **Strategy** — Develop a roadmap aligned with your business goals.
3. **Implementation** — Execute with careful monitoring and iteration.
4. **Optimization** — Continuously refine based on results and feedback.

## Conclusion

{topic} offers tremendous potential for those who approach it thoughtfully. By understanding the landscape and taking strategic action, you can position yourself for success.

{closing}

---

*This article was generated by content-automata.*
"""
        return post

    def _generate_social_copy(
        self, topic: str, key_points: List[str], tone: str
    ) -> str:
        """Generate social media copy variants."""
        points = ", ".join(key_points[:2])

        copies = [
            f"🚀 **{topic}** — Here's what you need to know:\n\n{points}\n\n"
            f"What's your take on this trend? Drop your thoughts below! 👇",
            f"💡 **{topic} Insight:**\n\nThe key is understanding how to apply these principles "
            f"to your specific context. Generic advice won't cut it anymore.\n\n"
            f"Read more in our latest article! 📖",
            f"📊 **{topic} by the numbers:**\n\nOrganizations leveraging {topic} are seeing:\n"
            f"✅ Increased efficiency\n✅ Better outcomes\n✅ Higher ROI\n\n"
            f"Is your business keeping up?",
        ]

        return "\n\n---\n\n".join(copies)

    def _generate_ad_copy(
        self, topic: str, key_points: List[str], tone: str
    ) -> str:
        """Generate advertisement copy."""
        return f"""**Headline:** Master {topic} in 2026

**Subheadline:** The comprehensive guide for forward-thinking professionals

**Body:**
Tired of information overload? Our guide cuts through the noise and delivers actionable insights you can implement today. From fundamentals to advanced strategies, we've got you covered.

**Call to Action:**
👉 [Download the Free Guide]
👉 [Schedule a Consultation]

**Benefits:**
• Save hours of research time
• Get proven strategies
• Learn from industry experts
• Stay ahead of the competition"""

    def _generate_headline(self, topic: str, tone: str) -> str:
        """Generate a compelling headline."""
        headlines = [
            f"The Ultimate Guide to {topic} in 2026",
            f"{topic}: Everything You Need to Know",
            f"Why {topic} Is the Future of Your Industry",
            f"10 Things You Didn't Know About {topic}",
            f"How to Master {topic} in 30 Days",
        ]
        return headlines[0]

    def _generate_meta_description(
        self, topic: str, key_points: List[str]
    ) -> str:
        """Generate an SEO meta description."""
        points = "; ".join(key_points[:2])
        return (
            f"Discover everything about {topic}. {points}. "
            f"A comprehensive guide with actionable insights, expert analysis, "
            f"and practical tips to help you succeed."
        )

    def _tone_greeting(self, tone: str) -> str:
        """Get a tone-appropriate greeting."""
        greetings = {
            "professional": "Welcome to this comprehensive analysis.",
            "casual": "Hey there! Let's dive into something exciting.",
            "persuasive": "Imagine what's possible when you get this right.",
            "humorous": "Buckle up — this is going to be fun and informative!",
            "authoritative": "Listen up: this is critical information.",
        }
        return greetings.get(tone, greetings["professional"])

    def _tone_closing(self, tone: str) -> str:
        """Get a tone-appropriate closing."""
        closings = {
            "professional": "We hope this analysis has been valuable. Please reach out with questions.",
            "casual": "Hope this helps! Let me know what you think.",
            "persuasive": "Don't wait — the time to act is now. Your future self will thank you.",
            "humorous": "And that's the tea! ☕ Hope you enjoyed the brain buffet.",
            "authoritative": "The information is clear. Now it's your move. Execute accordingly.",
        }
        return closings.get(tone, closings["professional"])
