"""Scheduling stage — formats and exports content."""

from __future__ import annotations

import csv
import io
import json
import logging
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

from content_automata.models import (
    ContentBrief,
    FinalContent,
    ScheduleExport,
    ScheduleResult,
)

logger = logging.getLogger(__name__)


class ContentScheduler:
    """Formats and schedules content for publishing.

    Supports Markdown, HTML, and CSV export formats with
    configurable scheduling options.
    """

    SUPPORTED_FORMATS = ["markdown", "html", "csv"]

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self._config = config or {}
        self._export_formats = self._config.get("scheduling", {}).get(
            "export_formats", ["markdown"]
        )
        self._output_dir = Path(
            self._config.get("scheduling", {}).get("output_dir", "./output")
        )
        logger.info(
            f"ContentScheduler initialized: formats={self._export_formats}, "
            f"output_dir='{self._output_dir}'"
        )

    def schedule(
        self, final: FinalContent, brief: ContentBrief
    ) -> ScheduleResult:
        """Format and schedule the final content package.

        Args:
            final: The complete content package with research, draft, and visuals.
            brief: The original content brief.

        Returns:
            A ScheduleResult with exported content artifacts.
        """
        topic = brief.topic
        logger.info(f"Scheduling content for '{topic}'")

        exports: List[ScheduleExport] = []

        for fmt in self._export_formats:
            if fmt not in self.SUPPORTED_FORMATS:
                logger.warning(f"Unsupported format '{fmt}', skipping")
                continue

            content = self._export(final, brief, fmt)
            file_path = self._save(content, topic, fmt)

            exports.append(
                ScheduleExport(
                    format=fmt,
                    content=content,
                    file_path=str(file_path) if file_path else None,
                )
            )

        # Default schedule: 1 day from now
        scheduled_date = datetime.now() + timedelta(days=1)

        return ScheduleResult(
            exports=exports,
            scheduled_date=scheduled_date,
            platform=brief.platform or "web",
        )

    def _export(
        self, final: FinalContent, brief: ContentBrief, fmt: str
    ) -> str:
        """Export content in the specified format."""
        exporters = {
            "markdown": self._export_markdown,
            "html": self._export_html,
            "csv": self._export_csv,
        }
        exporter = exporters.get(fmt)
        if exporter:
            return exporter(final, brief)
        raise ValueError(f"Unsupported export format: {fmt}")

    def _export_markdown(
        self, final: FinalContent, brief: ContentBrief
    ) -> str:
        """Export content as Markdown."""
        lines = [
            f"# {brief.topic}",
            "",
            f"*Generated by content-automata on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
            "",
            "---",
            "",
            "## Research Summary",
            "",
            final.research.summary,
            "",
            "## Key Points",
            "",
        ]
        for point in final.research.key_points:
            lines.append(f"- {point}")

        lines.extend(["", "---", "", "## Content", ""])
        if final.draft.blog_post:
            lines.append(final.draft.blog_post)

        lines.extend(["", "---", "", "## Visual Assets", ""])
        for img in final.visuals.images:
            lines.append(f"![{img.alt_text}]({img.url})")
            lines.append(f"*{img.alt_text}*")
            lines.append("")

        lines.extend(["", "---", "", "## Metadata", ""])
        lines.append(f"- **Tone:** {final.draft.tone}")
        lines.append(f"- **Word count:** {final.draft.word_count}")
        lines.append(f"- **Headline:** {final.draft.headline or 'N/A'}")
        lines.append(f"- **Scheduled:** {final.schedule.scheduled_date or 'N/A'}")

        return "\n".join(lines)

    def _export_html(
        self, final: FinalContent, brief: ContentBrief
    ) -> str:
        """Export content as HTML."""
        images_html = ""
        for img in final.visuals.images:
            images_html += f"""
    <figure>
        <img src="{img.url}" alt="{img.alt_text}" width="{img.width}" height="{img.height}" />
        <figcaption>{img.alt_text}</figcaption>
    </figure>"""

        key_points_html = "\n".join(
            f"        <li>{point}</li>" for point in final.research.key_points
        )

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{final.draft.meta_description or brief.topic}">
    <title>{brief.topic}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: #333; }}
        h1, h2, h3 {{ color: #1a1a1a; }}
        img {{ max-width: 100%; height: auto; border-radius: 8px; margin: 1rem 0; }}
        figure {{ margin: 2rem 0; text-align: center; }}
        figcaption {{ font-style: italic; color: #666; margin-top: 0.5rem; }}
        .meta {{ background: #f5f5f5; padding: 1rem; border-radius: 8px; margin-top: 2rem; }}
        hr {{ border: none; border-top: 1px solid #ddd; margin: 2rem 0; }}
    </style>
</head>
<body>
    <header>
        <h1>{brief.topic}</h1>
        <p><em>Generated by content-automata on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</em></p>
    </header>

    <hr>

    <section id="research">
        <h2>Research Summary</h2>
        <p>{final.research.summary}</p>

        <h3>Key Points</h3>
        <ul>
{key_points_html}
        </ul>
    </section>

    <hr>

    <section id="content">
        <h2>Content</h2>
        <div class="content-body">
            {final.draft.blog_post or ''}
        </div>
    </section>

    <hr>

    <section id="visuals">
        <h2>Visual Assets</h2>
        {images_html}
    </section>

    <hr>

    <section class="meta">
        <h2>Metadata</h2>
        <ul>
            <li><strong>Tone:</strong> {final.draft.tone}</li>
            <li><strong>Word count:</strong> {final.draft.word_count}</li>
            <li><strong>Headline:</strong> {final.draft.headline or 'N/A'}</li>
            <li><strong>Scheduled:</strong> {final.schedule.scheduled_date or 'N/A'}</li>
        </ul>
    </section>
</body>
</html>"""

    def _export_csv(
        self, final: FinalContent, brief: ContentBrief
    ) -> str:
        """Export content as CSV."""
        output = io.StringIO()
        writer = csv.writer(output)

        writer.writerow(["Field", "Value"])
        writer.writerow(["Topic", brief.topic])
        writer.writerow(["Tone", final.draft.tone])
        writer.writerow(["Headline", final.draft.headline or ""])
        writer.writerow(["Word Count", str(final.draft.word_count)])
        writer.writerow(["Meta Description", final.draft.meta_description or ""])
        writer.writerow(["Summary", final.research.summary])
        writer.writerow([])
        writer.writerow(["Key Points"])
        for point in final.research.key_points:
            writer.writerow(["", point])
        writer.writerow([])
        writer.writerow(["Blog Post", final.draft.blog_post or ""])
        writer.writerow(["Social Copy", final.draft.social_copy or ""])
        writer.writerow(["Ad Copy", final.draft.ad_copy or ""])
        writer.writerow([])
        writer.writerow(["Image URLs"])
        for img in final.visuals.images:
            writer.writerow(["", img.url, img.alt_text])
        writer.writerow([])
        writer.writerow(["Scheduled Date", str(final.schedule.scheduled_date or "")])

        return output.getvalue()

    def _save(self, content: str, topic: str, fmt: str) -> Optional[Path]:
        """Save exported content to a file."""
        try:
            self._output_dir.mkdir(parents=True, exist_ok=True)

            ext_map = {"markdown": "md", "html": "html", "csv": "csv"}
            ext = ext_map.get(fmt, "txt")

            safe_topic = topic.lower().replace(" ", "-").replace("/", "-")
            filename = f"{safe_topic}-{datetime.now().strftime('%Y%m%d-%H%M%S')}.{ext}"
            file_path = self._output_dir / filename

            file_path.write_text(content, encoding="utf-8")
            logger.info(f"Saved export: {file_path}")
            return file_path
        except Exception as e:
            logger.error(f"Failed to save export: {e}")
            return None
