"""Unified content model serialization.

Provides consistent serialization/deserialization for all
content-automata models across JSON, YAML, Markdown, and HTML
formats with a unified interface.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Type, TypeVar, Union

import yaml

from content_automata.models import (
    ContentBrief,
    ContentPackage,
    Draft,
    FinalContent,
    ResearchResult,
    ScheduleExport,
    ScheduleResult,
    VisualAsset,
    VisualsResult,
)

logger = logging.getLogger(__name__)

T = TypeVar("T", bound=Any)

# Supported export formats
SERIALIZATION_FORMATS = ["json", "yaml", "markdown", "html"]

# Template for Markdown export
MARKDOWN_TEMPLATE = """# {topic}

**Generated**: {date}
**Tone**: {tone}
**Word Count**: {word_count}
**Status**: {state}

---

## Research Summary

{research_summary}

### Key Points

{key_points}

---

## Content Draft

### Headline
{headline}

### Blog Post

{blog_post}

---

## Meta Description

{meta_description}

---

## Visual Assets

{visuals}

---

## Exports

{exports}

---

*Generated by content-automata v{version}*
"""

# Template for HTML export
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{meta_description}">
    <title>{topic}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: #333; }}
        h1, h2, h3 {{ color: #1a1a2e; }}
        .meta {{ color: #666; font-size: 0.9rem; }}
        .key-points li {{ margin-bottom: 0.5rem; }}
        img {{ max-width: 100%; height: auto; border-radius: 8px; margin: 1rem 0; }}
        hr {{ border: none; border-top: 1px solid #eee; margin: 2rem 0; }}
        .footer {{ color: #999; font-size: 0.8rem; text-align: center; margin-top: 3rem; }}
    </style>
</head>
<body>
    <article>
        <h1>{topic}</h1>
        <p class="meta">Generated: {date} | Tone: {tone} | Words: {word_count}</p>

        <hr>

        <h2>Research Summary</h2>
        <p>{research_summary}</p>

        <h3>Key Points</h3>
        <ul class="key-points">
{key_points_html}
        </ul>

        <hr>

        <h2>{headline}</h2>
        <div class="content">
{blog_post_html}
        </div>

        <hr>

        <h2>Visual Assets</h2>
{visuals_html}

        <hr>

        <div class="footer">
            <p>Generated by content-automata v{version}</p>
        </div>
    </article>
</body>
</html>
"""


class ContentSerializer:
    """Unified serializer/deserializer for content models.

    Supports multiple formats:
    - JSON: Structured data interchange
    - YAML: Human-readable configuration-oriented format
    - Markdown: Readable document format
    - HTML: Web-ready export format

    All serializers accept the same ContentPackage and produce
    consistent output with metadata.
    """

    def __init__(self, config: Optional[dict] = None):
        self._config = config or {}

    def serialize(
        self,
        package: ContentPackage,
        fmt: str = "json",
        **kwargs: Any,
    ) -> str:
        """Serialize a content package to the requested format.

        Args:
            package: ContentPackage to serialize.
            fmt: Output format (json, yaml, markdown, html).
            **kwargs: Additional format-specific options.

        Returns:
            Serialized string.

        Raises:
            ValueError: If format is not supported.
        """
        formatters = {
            "json": self._to_json,
            "yaml": self._to_yaml,
            "markdown": self._to_markdown,
            "md": self._to_markdown,
            "html": self._to_html,
        }

        formatter = formatters.get(fmt.lower())
        if not formatter:
            raise ValueError(
                f"Unsupported format '{fmt}'. "
                f"Supported: {SERIALIZATION_FORMATS}"
            )

        return formatter(package, **kwargs)

    def deserialize(
        self,
        data: str,
        fmt: str = "json",
    ) -> ContentPackage:
        """Deserialize data back to a ContentPackage.

        Args:
            data: String data to deserialize.
            fmt: Input format (json, yaml).

        Returns:
            Deserialized ContentPackage.
        """
        if fmt == "json":
            return self._from_json(data)
        elif fmt in ("yaml", "yml"):
            return self._from_yaml(data)
        else:
            raise ValueError(
                f"Deserialization from '{fmt}' not supported. "
                f"Use 'json' or 'yaml'."
            )

    def serialize_to_file(
        self,
        package: ContentPackage,
        path: str | Path,
        fmt: Optional[str] = None,
        **kwargs: Any,
    ) -> Path:
        """Serialize and write to a file.

        Detects format from file extension if not specified.

        Args:
            package: ContentPackage to serialize.
            path: Output file path.
            fmt: Output format (overrides extension detection).

        Returns:
            Path to the written file.
        """
        path = Path(path)
        if fmt is None:
            ext = path.suffix.lower().lstrip(".")
            fmt = ext if ext else "json"

        content = self.serialize(package, fmt, **kwargs)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        logger.info("Serialized package to %s (%s format)", path, fmt)
        return path

    def _to_json(self, package: ContentPackage, **kwargs: Any) -> str:
        """Serialize to JSON.

        Args:
            package: ContentPackage to serialize.
            **kwargs: Passed to json.dumps (indent, etc.).

        Returns:
            JSON string.
        """
        data = self._package_to_dict(package)
        indent = kwargs.get("indent", 2)
        return json.dumps(data, indent=indent, default=str, ensure_ascii=False)

    def _to_yaml(self, package: ContentPackage, **kwargs: Any) -> str:
        """Serialize to YAML.

        Args:
            package: ContentPackage to serialize.
            **kwargs: Passed to yaml.dump.

        Returns:
            YAML string.
        """
        data = self._package_to_dict(package)
        return yaml.dump(data, default_flow_style=False, allow_unicode=True, **kwargs)

    def _to_markdown(self, package: ContentPackage, **kwargs: Any) -> str:
        """Serialize to Markdown document.

        Args:
            package: ContentPackage to serialize.
            **kwargs: Format options.

        Returns:
            Markdown string.
        """
        brief = package.brief
        final = package.final

        # Format key points
        key_points = "\n".join(
            f"- {point}" for point in final.research.key_points
        ) if final.research.key_points else "- No key points extracted"

        # Format visuals
        visuals = ""
        for i, img in enumerate(final.visuals.images, 1):
            visuals += f"![{img.alt_text or 'Image'}]({img.url})\n\n"
        if not visuals:
            visuals = "- No visuals generated\n"

        # Format exports
        exports = ""
        for exp in final.schedule.exports:
            exports += f"- **{exp.format.upper()}**: {exp.file_path or 'in-memory'}\n"
        if not exports:
            exports = "- No exports generated\n"

        return MARKDOWN_TEMPLATE.format(
            topic=brief.topic,
            date=datetime.now().strftime("%Y-%m-%d %H:%M"),
            tone=final.draft.tone,
            word_count=final.draft.word_count,
            state=package.state.value,
            research_summary=final.research.summary or "No summary available",
            key_points=key_points,
            headline=final.draft.headline or "No headline",
            blog_post=final.draft.blog_post or "No blog post content",
            meta_description=final.draft.meta_description or "No meta description",
            visuals=visuals,
            exports=exports,
            version=package.version,
        )

    def _to_html(self, package: ContentPackage, **kwargs: Any) -> str:
        """Serialize to HTML document.

        Args:
            package: ContentPackage to serialize.
            **kwargs: Format options.

        Returns:
            HTML string.
        """
        brief = package.brief
        final = package.final

        # Format key points
        key_points_html = "\n".join(
            f"            <li>{point}</li>" for point in final.research.key_points
        ) if final.research.key_points else "            <li>No key points extracted</li>"

        # Format blog post HTML
        blog_post = final.draft.blog_post or "No blog post content"
        blog_post_html = blog_post.replace("\n\n", "</p>\n            <p>")
        blog_post_html = blog_post_html.replace("\n", "<br>\n            ")

        # Format visuals
        visuals_html = ""
        for img in final.visuals.images:
            visuals_html += (
                f'            <figure>\n'
                f'                <img src="{img.url}" alt="{img.alt_text}">\n'
                f'                <figcaption>{img.alt_text}</figcaption>\n'
                f'            </figure>\n'
            )
        if not visuals_html:
            visuals_html = "            <p>No visuals generated</p>\n"

        return HTML_TEMPLATE.format(
            topic=brief.topic,
            date=datetime.now().strftime("%Y-%m-%d %H:%M"),
            tone=final.draft.tone,
            word_count=final.draft.word_count,
            state=package.state.value,
            research_summary=final.research.summary or "No summary available",
            key_points_html=key_points_html,
            headline=final.draft.headline or "No headline",
            blog_post_html=blog_post_html,
            meta_description=final.draft.meta_description or "",
            visuals_html=visuals_html,
            version=package.version,
        )

    def _package_to_dict(self, package: ContentPackage) -> Dict[str, Any]:
        """Convert a ContentPackage to a plain dictionary.

        Args:
            package: The package to convert.

        Returns:
            Serializable dictionary representation.
        """
        return {
            "version": package.version,
            "state": package.state.value,
            "created_at": str(package.created_at),
            "completed_at": str(package.completed_at) if package.completed_at else None,
            "brief": {
                "topic": package.brief.topic,
                "keywords": package.brief.keywords,
                "target_audience": package.brief.target_audience,
                "tone": package.brief.tone,
                "format": package.brief.format,
                "platform": package.brief.platform,
                "custom_instructions": package.brief.custom_instructions,
            },
            "final": {
                "research": {
                    "topic": package.final.research.topic,
                    "summary": package.final.research.summary,
                    "key_points": package.final.research.key_points,
                    "sources": package.final.research.sources,
                    "outline": package.final.research.outline,
                },
                "draft": {
                    "headline": package.final.draft.headline,
                    "meta_description": package.final.draft.meta_description,
                    "tone": package.final.draft.tone,
                    "word_count": package.final.draft.word_count,
                    "blog_post": package.final.draft.blog_post,
                    "social_copy": package.final.draft.social_copy,
                    "ad_copy": package.final.draft.ad_copy,
                },
                "visuals": {
                    "images": [
                        {
                            "url": img.url,
                            "alt_text": img.alt_text,
                            "prompt": img.prompt,
                            "aspect_ratio": img.aspect_ratio,
                        }
                        for img in package.final.visuals.images
                    ],
                },
                "schedule": {
                    "exports": [
                        {
                            "format": exp.format,
                            "file_path": exp.file_path,
                            "created_at": str(exp.created_at),
                        }
                        for exp in package.final.schedule.exports
                    ],
                    "scheduled_date": str(package.final.schedule.scheduled_date)
                    if package.final.schedule.scheduled_date else None,
                    "platform": package.final.schedule.platform,
                },
            },
            "metadata": package.metadata,
        }

    def _from_json(self, data: str) -> ContentPackage:
        """Deserialize from JSON string.

        Args:
            data: JSON string.

        Returns:
            ContentPackage.
        """
        raw = json.loads(data)
        return self._dict_to_package(raw)

    def _from_yaml(self, data: str) -> ContentPackage:
        """Deserialize from YAML string.

        Args:
            data: YAML string.

        Returns:
            ContentPackage.
        """
        raw = yaml.safe_load(data)
        return self._dict_to_package(raw)

    def _dict_to_package(self, raw: Dict[str, Any]) -> ContentPackage:
        """Convert a dictionary back to a ContentPackage.

        Args:
            raw: Dictionary representation.

        Returns:
            Reconstructed ContentPackage.
        """
        brief_data = raw.get("brief", {})
        final_data = raw.get("final", {})

        brief = ContentBrief(
            topic=brief_data.get("topic", ""),
            keywords=brief_data.get("keywords", []),
            target_audience=brief_data.get("target_audience"),
            tone=brief_data.get("tone", "professional"),
            format=brief_data.get("format", "blog"),
            platform=brief_data.get("platform"),
            custom_instructions=brief_data.get("custom_instructions"),
        )

        research_data = final_data.get("research", {})
        research = ResearchResult(
            topic=research_data.get("topic", ""),
            summary=research_data.get("summary", ""),
            key_points=research_data.get("key_points", []),
            sources=research_data.get("sources", []),
            outline=research_data.get("outline", ""),
        )

        draft_data = final_data.get("draft", {})
        draft = Draft(
            headline=draft_data.get("headline"),
            meta_description=draft_data.get("meta_description"),
            tone=draft_data.get("tone", "professional"),
            word_count=draft_data.get("word_count", 0),
            blog_post=draft_data.get("blog_post"),
            social_copy=draft_data.get("social_copy"),
            ad_copy=draft_data.get("ad_copy"),
        )

        visuals_data = final_data.get("visuals", {})
        images = [
            VisualAsset(
                url=img["url"],
                alt_text=img.get("alt_text", ""),
                prompt=img.get("prompt", ""),
                aspect_ratio=img.get("aspect_ratio", "16:9"),
            )
            for img in visuals_data.get("images", [])
        ]
        visuals = VisualsResult(images=images)

        schedule_data = final_data.get("schedule", {})
        exports = [
            ScheduleExport(
                format=exp["format"],
                content=exp.get("content", ""),
                file_path=exp.get("file_path"),
            )
            for exp in schedule_data.get("exports", [])
        ]
        schedule = ScheduleResult(
            exports=exports,
            scheduled_date=None,
            platform=schedule_data.get("platform"),
        )

        return ContentPackage(
            brief=brief,
            final=FinalContent(
                research=research,
                draft=draft,
                visuals=visuals,
                schedule=schedule,
            ),
        )

    def list_formats(self) -> List[str]:
        """List all supported serialization formats.

        Returns:
            List of format name strings.
        """
        return SERIALIZATION_FORMATS.copy()
